language: ruby
dist: bionic
sudo: false
addons:
  chrome: stable
  postgresql: '10'
services:
  - mysql
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
bundler_args: --without development
before_script:
  - export RETRY_COUNT=3
  - bin/rake refinery:testing:dummy_app
script:
  - bin/rspec $EXTENSION/spec
env:
  - DB=postgresql EXTENSION=core
  - DB=postgresql EXTENSION=dragonfly
  - DB=postgresql EXTENSION=pages
  - DB=postgresql EXTENSION=images
  - DB=postgresql EXTENSION=resources
  - DB=mysql EXTENSION=core
  - DB=mysql EXTENSION=dragonfly
  - DB=mysql EXTENSION=pages
  - DB=mysql EXTENSION=images
  - DB=mysql EXTENSION=resources
notifications:
  email: true
  webhooks:
    - https://webhooks.gitter.im/e/b5d48907cdc89864b874
rvm:
  - 2.6
  - 2.5
