before_script: sh -e /etc/init.d/xvfb start
script: "export DISPLAY=:99.0 &&  bundle exec rake db:create db:migrate spec"
notifications:
  email:
    - parndt@gmail.com
    - ugis.ozolss@gmail.com
env:
  - DB=postgres
  - DB=mysql
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-2.0
  - jruby