before_install:
  - gem install bundler --pre
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
script: "DISPLAY=:99.0 bundle exec rspec ./*/spec"
notifications:
  email:
    - parndt@gmail.com
    - ugis.ozolss@gmail.com
  irc:
    - "irc.freenode.org#refinerycms"
env:
  - DB=postgresql SKIP_COV=true
  - DB=mysql SKIP_COV=true
rvm:
  - 1.8.7
  - 1.9.3
  - rbx
  - jruby
