name: CI

on: [push]
jobs:
  test:
    strategy:
      matrix:
        architecture: [x64]
        database: [postgresql]
        extension: [core, dragonfly, images, pages, resources]
        ruby: ['2.6.x']
      fail-fast: false
      max-parallel: 10
    runs-on: ubuntu-latest
    name: ${{ matrix.extension }} ${{ matrix.ruby }} ${{ matrix.database }}
    steps:
    - uses: actions/setup-ruby@v1.0.0
      with:
        architecture: ${{ matrix.architecture }}
        ruby-version: ${{ matrix.ruby }}
        version: ${{ matrix.ruby }}
    - uses: actions/checkout@v1
    - run: sudo apt-get update && sudo apt-get install libpq-dev libmysqlclient-dev libsqlite3-dev -y
    - id: cache-bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ matrix.ruby }}-gem-${{ matrix.database }}-${{ hashFiles('Gemfile.lock') }}
    - run: |
        bundle install --without development --path vendor/bundle
        bin/rake refinery:testing:dummy_app
      env:
        BUNDLE_JOBS: 4
        BUNDLE_PATH: vendor/bundle
        CI: true
        DB: ${{ matrix.database }}
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
    - run: bin/rspec ${{ matrix.extension }}/spec
      env:
        CI: true
        DB: ${{ matrix.database }}
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

